#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          encoderLeft,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          encoderRight,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     turntable,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * teleop_0.2.2.c
 * This file is part of Teleop
 *
 * Copyright (C) 2012 - EMC Squirrled
 *
 * Teleop is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Teleop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Teleop; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */


/* ===== INCLUDES ===== */

#include <JoystickDriver.c>

/* ===== DEFINES ===== */

#define JOYSTICK_UPDATE_TIME 10
#define MOTOR_UPDATE_TIME 5

#define DPAD_NONE -1
#define DPAD_UP 0
#define DPAD_DOWN 4
#define DPAD_LEFT 6
#define DPAD_RIGHT 2

/* ===== FUNCTIONS ===== */

void vInitializeRobot(void);
int fJoyToPower(signed short iJoy);

/* ===== TASKS ===== */

task ReadJoystick1();
task ReadJoystick2();
task UpdateDriveMotors();
task UpdateManipulators();

/* ===== STRUCTURES ===== */

typedef struct {
    signed byte iPower;
} oMotor;

/* ===== GLOBALS === */

oMotor oLeftMotor;
oMotor oRightMotor;
oMotor oTurnTable;
oMotor oLift;
int turntableEnabled;

/* ===== CODE ===== */

/* Task Main -- Entry point of the code */
task main() {
    // Initialize the robot and wait for the start of the match
    vInitializeRobot();
    waitForStart();

    // Start all tasks
    StartTask(ReadJoystick1);
    StartTask(ReadJoystick2);
    StartTask(UpdateDriveMotors);
    StartTask(UpdateManipulators);

    // Do nothing, for the tasks do it all
    while(1) wait10Msec(1000);
}

/* Task ReadJoystick1 --  */
task ReadJoystick1() {
    while(1) {
        getJoystickSettings(joystick);
        oLeftMotor.iPower = fJoyToPower(joystick.joy1_y1);
        oRightMotor.iPower = fJoyToPower(joystick.joy1_y2);
        if (joystick.joy1_TopHat == DPAD_UP) {
        	oLeftMotor.iPower = 25;
        	oRightMotor.iPower = 25;
      	}
      	if (joystick.joy1_TopHat == DPAD_DOWN) {
        	oLeftMotor.iPower = -25;
        	oRightMotor.iPower = -25;
      	}
      	if (joystick.joy1_TopHat == DPAD_LEFT) {
        	oLeftMotor.iPower = -50;
        	oRightMotor.iPower = 50;
      	}
      	if (joystick.joy1_TopHat == DPAD_RIGHT) {
        	oLeftMotor.iPower = 50;
        	oRightMotor.iPower = -50;
      	}

      	if(joy1Btn(9) && joy1Btn(10)) {
      		turntableEnabled = 1;
      	} else {
      		turntableEnabled = 0;
    	}

        wait1Msec(JOYSTICK_UPDATE_TIME);
    }
}

task ReadJoystick2() {
	while(1) {
		getJoystickSettings(joystick);
		oLift.iPower = 0;
		if(joystick.joy2_TopHat == DPAD_UP) {
			oLift.iPower = 85;
		}
		if(joystick.joy2_TopHat == DPAD_DOWN) {
			oLift.iPower = -20;
		}

		oTurnTable.iPower = 0;
		if(joystick.joy2_TopHat == DPAD_LEFT) {
			oTurnTable.iPower = -30;
		}
		if(joystick.joy2_TopHat == DPAD_RIGHT) {
			oTurnTable.iPower = 30;
		}

		wait1Msec(JOYSTICK_UPDATE_TIME);
    }
}

task UpdateDriveMotors() {
    while(1) {
        motor[driveLeft] = -oLeftMotor.iPower;
        motor[driveRight] = oRightMotor.iPower;
        wait1Msec(MOTOR_UPDATE_TIME);
    }
}

task UpdateManipulators() {
	while(1) {
        motor[turntable] = oTurnTable.iPower;
        motor[lift] = oLift.iPower;
		wait1Msec(MOTOR_UPDATE_TIME);
	}
}

void vInitializeRobot() {
    oLeftMotor.iPower = 0;
    oRightMotor.iPower = 0;
    oTurnTable.iPower = 0;
    turntableEnabled = 0;
    oLift.iPower = 0;
}

float fJoyToPower(signed short iJoy) {
    int fPower = (int) (abs(iJoy) - 27);
    if (fPower < 0) {
    	fPower = 0;
	} else if (iJoy < 0) {
		fPower = -fPower;
	}
	if (fPower > 100) {
		fPower = 100;
	} else if (fPower < -100) {
		fPower = -100;
	}
    return fPower;
}
