#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          claw,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1) {
		while(SensorValue[touch]) {
			motor[claw] = -100;
			nxtDisplayTextLine(1, "%d", nMotorEncoder[claw]);
			wait10Msec(1);
		}
		motor[claw] = 100;
	}
}
