#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          driveLeft,   tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          driveRight,  tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Gyro_Test.c
* This file is part of Gyro_Test
*
* Copyright (C) 2012 - EMC Squirrled
*
* Gyro_Test is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* Gyro_Test is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Autonomous; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor,
* Boston, MA  02110-1301  USA
*/

/* ===== INCLUDES ===== */

#include <JoystickDriver.c>
#include "includes/rdpartyrobotcdr-3.1/drivers/hitechnic-gyro.h"

/* ===== DEFINES ===== */

#define INCHES_PER_DEGREE (360*(1/(4*PI)))

#define DISTANCE_TO_RACK 30
#define DISTANCE_BETWEEN_ROWS 10
#define DISTANCE_TO_PLACE 5

#define ARM_UP 255
#define ARM_DOWN 0

#define DRIVE_SPEED 100
#define TURN_SPEED 100

/* ===== FUNCTIONS ===== */

void vTurnLeft(int iDegrees, short iPower);
void vTurnRight(int iDegrees, short iPower);
void vWaitForTurn(int iDegrees);
void vOnLeft(short iPower);
void vOnRight(short iPower);
void vOffLeft();
void vOffRight();

/* ===== CODE ===== */

/* Task Main -- Entry point of the code */
task main() {
	HTGYROstartCal(gyro);
	wait1Msec(1000);
	vTurnLeft(180, 25);
	wait1Msec(500);
	vTurnRight(180, 25);
}

void vTurnLeft(int iDegrees, short iPower) {
	vOnLeft(-1 * iPower);
	vOnRight(iPower);

	vWaitForTurn(iDegrees);

	vOffLeft();
	vOffRight();

	return;
}

void vTurnRight(int iDegrees, short iPower) {
	vOnLeft(iPower);
	vOnRight(-1 * iPower);

	vWaitForTurn(iDegrees);

	vOffLeft();
	vOffRight();
}

void vWaitForTurn(int iDegrees) {
	bool bTurning;
	float fAreaUnderVelocity, fAverageGyro, fCumulativeDegrees, fGyroVal, fTotalGyro, fDeltaTime;
	bTurning = true;
	fCumulativeDegrees = 0.0;

	ClearTimer(T1);
	while(bTurning) {
		fTotalGyro = 0.0;
		for(int i = 0; i < 10; i++) {
			fGyroVal = abs(HTGYROreadRot(gyro));
			fTotalGyro += fGyroVal;
			wait1Msec(1);
		}
		fAverageGyro = fTotalGyro / 10;
		fDeltaTime = (float) time1[T1];
		ClearTimer(T1);
		fAreaUnderVelocity = fAverageGyro * (fDeltaTime / 1000);
		fCumulativeDegrees += fAreaUnderVelocity;
		if((int) fCumulativeDegrees >= iDegrees) bTurning = false;
	}

	return;
}

void vOffLeft() {
	vOnLeft(0);
	return;
}

void vOffRight() {
	vOnRight(0);
	return;
}

void vOnLeft(short iPower) {
	motor[driveLeft] = iPower;
	return;
}

void vOnRight(short iPower) {
	motor[driveRight] = iPower;
	return;
}
