#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          driveLeft,   tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          driveRight,  tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Gyro_Test.c
* This file is part of Gyro_Test
*
* Copyright (C) 2012 - EMC Squirrled
*
* Gyro_Test is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* Gyro_Test is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Autonomous; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor,
* Boston, MA  02110-1301  USA
*/

/* ===== INCLUDES ===== */

#include <JoystickDriver.c>
#include "../includes/rdpartyrobotcdr-3.1/drivers/hitechnic-gyro.h"
#include "../includes/rdpartyrobotcdr-3.1/drivers/hitechnic-irseeker-v2.h"

/* ===== DEFINES ===== */

#define INCHES_PER_DEGREE (360*(1/(4*PI)))

#define DISTANCE_TO_RACK 30
#define DISTANCE_BETWEEN_ROWS 10
#define DISTANCE_TO_PLACE 5

#define ARM_UP 255
#define ARM_DOWN 0

#define DRIVE_SPEED 100
#define TURN_SPEED 100

/* ===== FUNCTIONS ===== */

void vInitializeRobot(void);
void vMoveForward(int iDistance, short iPower);
void vMoveBackward(int iDistance, short iPower);
void vTurnLeft(int iDegrees, short iPower);
void vTurnRight(int iDegrees, short iPower);
void vWaitForTurn(int iDegrees);
void vOnLeft(short iPower);
void vOnRight(short iPower);
void vOffLeft();
void vOffRight();
void vResetEncoders();
void vReleaseRing();
int iBeacon();

/* ===== CODE ===== */

/* Task Main -- Entry point of the code */
task main() {
	vTurnLeft(90, TURN_SPEED);
}

void vInitializeRobot() {
	vOffLeft();
	vOffRight();
	servo[arm] = ARM_DOWN;
}

int iBeacon() {
	int irSensor[5];
	int val;
	HTIRS2readAllACStrength(infrared, irSensor[0], irSensor[1], irSensor[2], irSensor[3], irSensor[4]);
	if((irSensor[1] != 0 && irSensor[2] != 0) && (abs(irSensor[1] - irSensor[2]) < 2)) {
		val = 1;
	} else {
		val = 0;
	}
	return val;
}

void vReleaseRing() {
	vResetEncoders();
	motor[claw] = -100;
	while(nMotorEncoder[claw] > -3000);
	motor[claw] = 0;
	return;
}

void vResetEncoders() {
	nMotorEncoder[claw] = 0;
	nMotorEncoder[encoderLeft] = 0;
	nMotorEncoder[encoderRight] = 0;
	return;
}

void vMoveForward(int iDistance, short iPower) {
	int iTargetVal = iDistance * INCHES_PER_DEGREE;

	vResetEncoders();

	vOnLeft(iPower);
	vOnRight(iPower);

	while(nMotorEncoder[encoderLeft] < iTargetVal || nMotorEncoder[encoderRight] < iTargetVal);

	vOffLeft();
	vOffRight();

	return;
}

void vMoveBackward(int iDistance, short iPower) {
	int iTargetVal = (-1 * iDistance) * INCHES_PER_DEGREE;

	vResetEncoders();

	vOnLeft(-1 * iPower);
	vOnRight(-1 * iPower);

	while(nMotorEncoder[encoderLeft] > iTargetVal || nMotorEncoder[encoderRight] > iTargetVal);

	vOffLeft();
	vOffRight();

	return;
}

void vTurnLeft(int iDegrees, short iPower) {
	vOnLeft(-1 * iPower);
	vOnRight(iPower);

	vWaitForTurn(iDegrees);

	vOffLeft();
	vOffRight();

	return;
}

void vTurnRight(int iDegrees, short iPower) {
	vOnLeft(iPower);
	vOnRight(-1 * iPower);

	vWaitForTurn(iDegrees);

	vOffLeft();
	vOffRight();
}

void vWaitForTurn(int iDegrees) {
	bool bTurning;
	int iGyroVal, iTotalGyro, iDeltaTime;
	float fAreaUnderVelocity, fAverageGyro, fCumulativeDegrees;
	bTurning = true;
	fCumulativeDegrees = 0.0;
	ClearTimer(T1);

	while(bTurning) {
		iTotalGyro = 0;

		for(static int i = 0; i < 10; i++) {
		iGyroVal = abs(HTGYROreadRot(gyro)) < 2 ? 0 : abs(HTGYROreadRot(gyro));
			iTotalGyro += iGyroVal;
			wait1Msec(1);
		}

		fAverageGyro = (iTotalGyro / 10);

		iDeltaTime = time1[T1];
		ClearTimer(T1);

		fAreaUnderVelocity = ((fAverageGyro * iDeltaTime) / 1000);
		fCumulativeDegrees += fAreaUnderVelocity;

		if(fCumulativeDegrees >= iDegrees) bTurning = false;
	}

	return;
}

void vOffLeft() {
	vOnLeft(0);
	return;
}

void vOffRight() {
	vOnRight(0);
	return;
}

void vOnLeft(short iPower) {
	motor[driveLeft] = iPower;
	return;
}

void vOnRight(short iPower) {
	motor[driveRight] = iPower;
	return;
}
